name: autolog_app

description: "Application for financial control and detailed recording of vehicle maintenance."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  firebase_auth: ^6.4.0
  firebase_crashlytics: ^5.2.6
  google_sign_in: ^6.3.0
  flutter_native_splash: ^2.4.7
  package_info_plus: ^10.2.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.5

flutter_native_splash:
  image: assets/images/autolog-logo.png
  color: "#2963F7"

  android_12:
    image: assets/images/autolog-logo.png
    color: "#2963F7"
    icon_background_color: "#2963F7"

  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.5
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4
  fake_cloud_firestore: ^4.2.0
  firebase_auth_mocks: ^0.15.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#2963F7"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/autolog-logo.png
    - assets/images/google-logo.png
    - assets/images/image-top-login.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Thin.ttf